version: '3.8'

services:
  api:
    container_name: latino-editor-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: "base"
    command: bash -c "npm install && npm run build && npm run start:dev"
    ports:
      - 3000:3000
    networks:
      - latino-editor-api
    working_dir: /app
    volumes:
      - .:/app
    restart: unless-stopped

  sqliteweb:
    image: tomdesinto/sqliteweb
    ports:
      - 8080:8080
    volumes:
      - ./data/latino-editor.db:/db/latino-editor.db
    command: latino-editor.db

networks:
  latino-editor-api:
