version: '3.8'

services:
  dev:
    container_name: latino-editor_backend_dev
    image: latino-editor-backend-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - latino-editor-backend
    volumes:
      - /usr/src/app/dist
      - /usr/src/app/node_modules
      - .:/usr/src/app
    restart: unless-stopped

  prod:
    container_name: latino-editor_backend_prod
    image: latino-editor-backend-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - latino-editor-backend
    volumes:
      - /usr/src/app/dist
      - /usr/src/app/node_modules
      - .:/usr/src/app
    restart: unless-stopped

networks:
  latino-editor-backend:
